FROM condaforge/miniforge3:latest

# 创建 Conda 虚拟环境
RUN mamba create -n myenv python=3.9 -y && \
    mamba install -n myenv -c conda-forge mamba -y && \
    mamba clean --all -f -y

# 激活虚拟环境
RUN source activate myenv
# 安装 PyTorch 等依赖
RUN pip install torch torchvision torchaudio
