FROM ubuntu:20.04
SHELL ["/bin/bash", "-c"]
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install wget -y && apt-get clean all

RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
    bash Miniconda3-latest-Linux-x86_64.sh -b -p /opt/miniconda && \
    /opt/miniconda/bin/conda init bash && \
    rm -rf Miniconda3-latest-Linux-x86_64.sh && \
    rm -rf /var/lib/apt/lists/*

ENV PATH=/opt/miniconda/bin:$PATH

RUN conda create -n deeptb python=3.8 -c conda-forge -y && \
    conda init && \
    source activate deeptb && \
    git clone git@github.com:deepmodeling/DeePTB.git && \
    cd ./deeptb && \
    pip install . && \
    conda clean --all -y && \
    rm -rf /root/.cache/pip && \
    echo "source activate deeptb" >> ~/.bashrc