import importlib.metadata

try:
    from ._version import version as __version__
except ImportError:
    import warnings
    warnings.warn("Failed to find (autogenerated) _version.py. This might be because you are installing from GitHub's tarballs, use the PyPI ones.")
    __version__ = "unknown"