name: Bug Report
description: Create a report for problems with DeePTB
labels: [Bug]
assignees: zhanghao
body:
- type: textarea
  attributes:
    label: Describe the bug
    description: |
      A clear and concise description of what the bug is. The bug may results in:
      - abnormal interruption of the program,
      - systematic or randomized numerical error, or
      - relatively low efficiency.
  validations:
    required: true

- type: textarea
  attributes:
    label: Expected behavior
    description: |
      A clear and concise description of what you expected to happen.

- type: textarea
  attributes:
    label: To Reproduce
    description: |
      Steps to reproduce the behavior:
      1. [e.g. clone the source code from ...]
      2. [e.g. install DeePTB ...]
      3. [e.g. run DeePTB with ...]

      It is recommended to attach your calculation case here for the developers to reproduce the bug.

- type: textarea
  attributes:
    label: Environment
    description: |
      - OS: [e.g. Ubuntu 20.04]
      - Dependencies: [e.g. PyTorch, SciPy, NumPy, ...]

- type: textarea
  attributes:
    label: Additional Context
    description: |
      Add any other context about the problem here.
- type: markdown
  attributes:
    value: >
      Thanks for contributing 🎉!
