name: Feature Request
description: Suggest something more for DeePTB to do
labels: [Feature]
assignees: zhanghao

body:
- type: textarea
  attributes:
    label: Background
    description: |
      A clear and concise description of why this new feature is important.
  validations:
    required: true

- type: textarea
  attributes:
    label: Describe the solution you'd like
    description: |
      A clear and concise description of what you want to happen.
  validations:
    required: true

- type: textarea
  attributes:
    label: Additional Context
    description: |
      Add any other context or screenshots about the feature request here.

- type: markdown
  attributes:
    value: >
      Thanks for contributing 🎉!