name: Help Wanted
description: For general questions or assistance.
labels: [Help wanted]
assignees: zhanghao

body:
- type: textarea
  attributes:
    label: Details
    description: |
      Want to use DeePTB for certain system? Facing problems when installing DeePTB? Don't know how to choose a good parameter? Feel free to reach us, and we'll do our best to help!
  validations:
    required: true
- type: markdown
  attributes:
    value: >
      Thanks for contributing 🎉!
