name: Tests
description: Regarding tests of DeePTB
labels: [Test]
assignees: zhanghao

body:
- type: textarea
  attributes:
    label: Describe Current Status and Possible Solution

  validations:
    required: true

- type: textarea
  attributes:
    label: Additional Context
    description: |
      Add any other context or screenshots about the enhancement here.

- type: markdown
  attributes:
    value: >
      Thanks for contributing 🎉!
