import sys
import ase
import ase.io
import argparse
import numpy as np
import matplotlib.pyplot as plt

# from dptb.Parameters import Paras
# from dptb.nnet import Model


def  band_plot(args:argparse.Namespace):
    """
    Plot the band structure.

    Input: 
    ----- 

    """
    input_file = args.input_file
    fp = open(input_file)
    paras = Paras(fp, args.command, args.nn_off)
    mdl = Model(paras)
    mdl.loadmodel()

    if args.struct:
        strase = ase.io.read(args.struct,format=args.format)
    elif hasattr(paras,'struct') and hasattr(paras,'format'): 
        strase = ase.io.read(paras.struct,format=paras.format)
    else:
        print('please set the stucture and format tag.')
        sys.exit()

    mdl.structinput(strase)
    mdl.nnhoppings()
    mdl.SKhoppings()
    
    lat = strase.cell.get_bravais_lattice()
    #print(lat.description())
    #lat.plot_bz(show=True)
    special_kp = lat.get_special_points()
    #spmap['M'] = np.array([0.5,0.5,1])
    for ikey in paras.HighSymKps.keys():
        special_kp[ikey] = np.array(paras.HighSymKps[ikey])

    kpath=strase.cell.bandpath(paras.KPATH, npoints=paras.nkpoints)
    xlist, high_sym_kpoints, labels = kpath.get_linear_kpoint_axis()
    klist = kpath.kpts

    if args.nn_off:
        mdl.SKcorrection()
        mdl.HSmat(hoppings = mdl.hoppings_corr, overlaps = mdl.overlaps_corr , 
              onsiteEs = mdl.onsiteEs_corr, onsiteSs = mdl.onsiteSs_corr)
    else:
        mdl.HSmat(hoppings = mdl.skhoppings, overlaps = mdl.skoverlaps , 
              onsiteEs = mdl.onsiteEs, onsiteSs = mdl.onsiteSs)

    eigks = mdl.Eigenvalues(kpoints = klist)
    eigksnp =  eigks.detach().numpy()
    
    nk = eigksnp.shape[0]
    ValElec = np.asarray(mdl.bondbuild.ProjValElec)
    nume = np.sum(ValElec[mdl.bondbuild.TypeID])
    numek = nume * nk//paras.SpinDeg
    sorteigs =  np.sort(np.reshape(eigksnp,[-1]))
    EF=(sorteigs[numek] + sorteigs[numek-1])/2

    if paras.band_range != None:
        emax =  paras.band_range[1]
        emin =  paras.band_range[0]
    else:
        emin = np.min(eigksnp - EF)
        emax = np.max(eigksnp - EF)

    # uncomment in server without UI
    plt.switch_backend('agg')           
    plt.figure(figsize=(5,5),dpi=200)

    for i in range(eigksnp.shape[1]):
        plt.plot(xlist, eigksnp[:,i] - EF,'r-',lw=1)
    for ii in high_sym_kpoints:
        plt.axvline(ii,color='gray',lw=1,ls='--')

    plt.axhline(0,ls='-.',c='gray')
    #plt.legend(loc=1,framealpha=1)
    plt.tick_params(direction='in')
    plt.ylim(emin,emax)
    plt.xlim(xlist.min(),xlist.max())
    plt.ylabel('E - EF (eV)',fontsize=12)
    plt.yticks(fontsize=12)
    plt.xticks(high_sym_kpoints,labels,fontsize=12)
    plt.savefig('./band.png',dpi=100)
    np.save('band_structure.npy',{'xlist':xlist,'eigenvalues':eigksnp,'Efermi':EF,'high_sym_kpoints':high_sym_kpoints,'labels':labels})

    
    plotcode=[["import numpy as np"],
    ["import matplotlib.pyplot as plt"],
    ["band_structure = np.load('band_structure.npy',allow_pickle=True).tolist()"],
    ["plt.switch_backend('agg')           "],
    ["plt.figure(figsize=(5,5),dpi=200)"],
    ["for i in range(band_structure['eigenvalues'].shape[1]):"],
    ["    plt.plot(band_structure['xlist'], band_structure['eigenvalues'][:,i] - band_structure['Efermi'],'r-',lw=1)"],
    ["for ii in band_structure['high_sym_kpoints']:"],
    ["    plt.axvline(ii,color='gray',lw=1,ls='--')"],
    ["plt.axhline(0,ls='-.',c='gray')"],
    ["#plt.legend(loc=1,framealpha=1)"],
    ["plt.tick_params(direction='in')"],
    ["#plt.ylim(emin,emax)"],
    ["plt.xlim(band_structure['xlist'].min(),band_structure['xlist'].max())"],
    ["plt.ylabel('E - EF (eV)',fontsize=12)"],
    ["plt.yticks(fontsize=12)"],
    ["plt.xticks(band_structure['high_sym_kpoints'],band_structure['labels'],fontsize=12)"],
    ["plt.savefig('./band_plot.png',dpi=100)"]]
    
    f=open('showband.py','w')
    for iraw in plotcode:
        print(iraw[0],file=f)
 



def DFTBP_band_plot(structase, pathstr:str, high_sym_kpoints_dict:dict, 
                    number_in_line:list,band_file:str,
                    ylim=None):
    """The function `DFTBP_band_plot` will plot band structure from DFTB+ output file band_tot.dat.
    Note that the band_tot.dat file is generated by DFTB+ code with cmd: dp_bands band.out band. The detailed 
    operation is in https://dftbplus-recipes.readthedocs.io/en/latest/basics/bandstruct.html.
    
    It takes in a structure, a string of high symmetry points, a dictionary of high symmetry points, 
    the numbers of k-points in each line and the band file. It plots the band structure. 
      

    Parameters:
    -----------
    structase: ase structure object
    pathstr: str
        a string that defines the path in reciprocal space.
    high_sym_kpoints: dict
        a dictionary of high symmetry points
    number_in_line: int
        the numbers of k-points in each line
    band_file: str
        the band file generated by DFTB+ code
    ylim: list[float]
        the ylimit of the band structure plot

    Returns:
    --------
    None
    
    Examples:
    ---------
    >>> struct = read('struct.vasp') or read('struct.gen')
    >>> pathstr = ["Z-G","G-X","X-P"]
    >>> high_sym_kpoints_dict = {
    >>> "G": [0, 0, 0],
    >>> "X": [0, 0, 0.5],
    >>> "P": [0.25, 0.25, 0.25],
    >>> "Z": [0.5, 0.5, -0.5]}
    >>> number_in_line = [21,45,10]
    >>> DFTBP_band_plot(struct, pathstr, high_sym_kpoints_dict, number_in_line,band_file='band_tot.dat')
    """

    kpath = []
    klist = []

    for i  in range(len(pathstr)):
        kline = (pathstr[i].split('-'))
        kpath.append([high_sym_kpoints_dict[kline[0]],high_sym_kpoints_dict[kline[1]]])
        kline_list = np.linspace(high_sym_kpoints_dict[kline[0]], high_sym_kpoints_dict[kline[1]], number_in_line[i])
        klist.append(kline_list)
        if i == 0:  
            klabels = [(pathstr[i].split('-')[0])]
        else:
            if pathstr[i].split('-')[0] == pathstr[i-1].split('-')[1]:
                klabels.append(pathstr[i].split('-')[0])
            else:
                klabels.append(pathstr[i-1].split('-')[1] + '|' + pathstr[i].split('-')[0])
            if i == len(pathstr)-1:
                klabels.append(pathstr[i].split('-')[1])

    kpath = np.asarray(kpath)
    klist = np.concatenate(klist)


    rev_latt = np.mat(structase.cell).I.T
    #rev_latt = 2*np.pi*np.mat(ase_struct.cell).I
    kdiff = kpath[:,1] - kpath[:,0]
    kdiff_cart = np.asarray(kdiff * rev_latt)
    kdist  = np.linalg.norm(kdiff_cart,axis=1)

    xlist_label = [0] 
    for i in range(len(kdist)):
        if i == 0:
            xlist = np.linspace(0,kdist[i],number_in_line[i])
        else:
            xlist = np.concatenate([xlist, xlist[-1] + np.linspace(0,kdist[i],number_in_line[i])])
        xlist_label.append(xlist[-1])
    

    eigs=[]
    with open(band_file) as f:
        for line in f.readlines():
            eig=[]
            line_ik = line.split()
            for ie in range(1,len(line_ik)):
                eig.append(float(line_ik[ie]))
            eigs.append(eig)
                
    eigs = np.array(eigs)

    for i in range(eigs.shape[1]):
        plt.plot(xlist,eigs[:,i],'b')
    for i in xlist_label:
        plt.axvline(i, color='k', linestyle='--')
    plt.xticks(xlist_label,klabels,fontsize=12)
    if ylim:
        plt.ylim(ylim[0],ylim[1])
    plt.ylabel('Energy (eV)')
    plt.show()
    return
    
   